[book]
authors = ["Andreas Peters"]
language = "en"
multilingual = false
src = "src"
title = "ClusterD - Continued development of Apache Mesos"

[preprocessor.open-on-gh]
command = "mdbook-open-on-gh"
renderer = ["html"]

[output.html]
git-repository-url = "https://github.com/m3scluster/clusterd-docs/"
